/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PlaygroundEvidenceRouteImport } from './routes/playground.evidence'
import { Route as AppInterviewsConsoleRouteImport } from './routes/app.interviews.console'
import { Route as AppJourneyIdRouteImport } from './routes/app.journey.$id'
import { Route as AppReportsIdRouteImport } from './routes/app.reports.$id'
import { Route as AppRolesNewRouteImport } from './routes/app.roles.new'
import { Route as AppReportsIdEvidenceRouteImport } from './routes/app.reports.$id.evidence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PlaygroundEvidenceRoute = PlaygroundEvidenceRouteImport.update({
  id: '/playground/evidence',
  path: '/playground/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsConsoleRoute = AppInterviewsConsoleRouteImport.update({
  id: '/interviews/console',
  path: '/interviews/console',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyIdRoute = AppJourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesNewRoute = AppRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIdEvidenceRoute = AppReportsIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app/': typeof AppIndexRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app': typeof AppIndexRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app/': typeof AppIndexRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/discovery'
    | '/playground/evidence'
    | '/app/'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/new'
    | '/app/reports/$id/evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/playground/evidence'
    | '/app'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/new'
    | '/app/reports/$id/evidence'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/discovery'
    | '/playground/evidence'
    | '/app/'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/new'
    | '/app/reports/$id/evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiscoveryRoute: typeof DiscoveryRoute
  PlaygroundEvidenceRoute: typeof PlaygroundEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/playground/evidence': {
      id: '/playground/evidence'
      path: '/playground/evidence'
      fullPath: '/playground/evidence'
      preLoaderRoute: typeof PlaygroundEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews/console': {
      id: '/app/interviews/console'
      path: '/interviews/console'
      fullPath: '/app/interviews/console'
      preLoaderRoute: typeof AppInterviewsConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey/$id': {
      id: '/app/journey/$id'
      path: '/journey/$id'
      fullPath: '/app/journey/$id'
      preLoaderRoute: typeof AppJourneyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$id': {
      id: '/app/reports/$id'
      path: '/reports/$id'
      fullPath: '/app/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/new': {
      id: '/app/roles/new'
      path: '/roles/new'
      fullPath: '/app/roles/new'
      preLoaderRoute: typeof AppRolesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$id/evidence': {
      id: '/app/reports/$id/evidence'
      path: '/evidence'
      fullPath: '/app/reports/$id/evidence'
      preLoaderRoute: typeof AppReportsIdEvidenceRouteImport
      parentRoute: typeof AppReportsIdRoute
    }
  }
}

interface AppReportsIdRouteChildren {
  AppReportsIdEvidenceRoute: typeof AppReportsIdEvidenceRoute
}

const AppReportsIdRouteChildren: AppReportsIdRouteChildren = {
  AppReportsIdEvidenceRoute: AppReportsIdEvidenceRoute,
}

const AppReportsIdRouteWithChildren = AppReportsIdRoute._addFileChildren(
  AppReportsIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInterviewsConsoleRoute: typeof AppInterviewsConsoleRoute
  AppJourneyIdRoute: typeof AppJourneyIdRoute
  AppReportsIdRoute: typeof AppReportsIdRouteWithChildren
  AppRolesNewRoute: typeof AppRolesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInterviewsConsoleRoute: AppInterviewsConsoleRoute,
  AppJourneyIdRoute: AppJourneyIdRoute,
  AppReportsIdRoute: AppReportsIdRouteWithChildren,
  AppRolesNewRoute: AppRolesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiscoveryRoute: DiscoveryRoute,
  PlaygroundEvidenceRoute: PlaygroundEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
