/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PlaygroundEvidenceRouteImport } from './routes/playground.evidence'
import { Route as AppCandidatesIndexRouteImport } from './routes/app.candidates.index'
import { Route as AppCandidatesIdRouteImport } from './routes/app.candidates.$id'
import { Route as AppInterviewsIndexRouteImport } from './routes/app.interviews.index'
import { Route as AppInterviewsIdRouteImport } from './routes/app.interviews.$id'
import { Route as AppInterviewsConsoleRouteImport } from './routes/app.interviews.console'
import { Route as AppJourneyIdRouteImport } from './routes/app.journey.$id'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppReportsIdRouteImport } from './routes/app.reports.$id'
import { Route as AppRolesIndexRouteImport } from './routes/app.roles.index'
import { Route as AppRolesIdRouteImport } from './routes/app.roles.$id'
import { Route as AppRolesNewRouteImport } from './routes/app.roles.new'
import { Route as AppReportsIdEvidenceRouteImport } from './routes/app.reports.$id.evidence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PlaygroundEvidenceRoute = PlaygroundEvidenceRouteImport.update({
  id: '/playground/evidence',
  path: '/playground/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdRoute = AppInterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsConsoleRoute = AppInterviewsConsoleRouteImport.update({
  id: '/interviews/console',
  path: '/interviews/console',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyIdRoute = AppJourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIdRoute = AppRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesNewRoute = AppRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIdEvidenceRoute = AppReportsIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app/': typeof AppIndexRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app': typeof AppIndexRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/candidates': typeof AppCandidatesIndexRoute
  '/app/interviews': typeof AppInterviewsIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/roles': typeof AppRolesIndexRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/playground/evidence': typeof PlaygroundEvidenceRoute
  '/app/': typeof AppIndexRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/interviews/console': typeof AppInterviewsConsoleRoute
  '/app/journey/$id': typeof AppJourneyIdRoute
  '/app/reports/$id': typeof AppReportsIdRouteWithChildren
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/new': typeof AppRolesNewRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/reports/$id/evidence': typeof AppReportsIdEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/discovery'
    | '/playground/evidence'
    | '/app/'
    | '/app/candidates/$id'
    | '/app/interviews/$id'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/$id'
    | '/app/roles/new'
    | '/app/candidates/'
    | '/app/interviews/'
    | '/app/reports/'
    | '/app/roles/'
    | '/app/reports/$id/evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/playground/evidence'
    | '/app'
    | '/app/candidates/$id'
    | '/app/interviews/$id'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/$id'
    | '/app/roles/new'
    | '/app/candidates'
    | '/app/interviews'
    | '/app/reports'
    | '/app/roles'
    | '/app/reports/$id/evidence'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/discovery'
    | '/playground/evidence'
    | '/app/'
    | '/app/candidates/$id'
    | '/app/interviews/$id'
    | '/app/interviews/console'
    | '/app/journey/$id'
    | '/app/reports/$id'
    | '/app/roles/$id'
    | '/app/roles/new'
    | '/app/candidates/'
    | '/app/interviews/'
    | '/app/reports/'
    | '/app/roles/'
    | '/app/reports/$id/evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiscoveryRoute: typeof DiscoveryRoute
  PlaygroundEvidenceRoute: typeof PlaygroundEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/playground/evidence': {
      id: '/playground/evidence'
      path: '/playground/evidence'
      fullPath: '/playground/evidence'
      preLoaderRoute: typeof PlaygroundEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/candidates/': {
      id: '/app/candidates/'
      path: '/candidates'
      fullPath: '/app/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/$id': {
      id: '/app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/app/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews/': {
      id: '/app/interviews/'
      path: '/interviews'
      fullPath: '/app/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews/$id': {
      id: '/app/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/app/interviews/$id'
      preLoaderRoute: typeof AppInterviewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews/console': {
      id: '/app/interviews/console'
      path: '/interviews/console'
      fullPath: '/app/interviews/console'
      preLoaderRoute: typeof AppInterviewsConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey/$id': {
      id: '/app/journey/$id'
      path: '/journey/$id'
      fullPath: '/app/journey/$id'
      preLoaderRoute: typeof AppJourneyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$id': {
      id: '/app/reports/$id'
      path: '/reports/$id'
      fullPath: '/app/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/': {
      id: '/app/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/$id': {
      id: '/app/roles/$id'
      path: '/roles/$id'
      fullPath: '/app/roles/$id'
      preLoaderRoute: typeof AppRolesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/new': {
      id: '/app/roles/new'
      path: '/roles/new'
      fullPath: '/app/roles/new'
      preLoaderRoute: typeof AppRolesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$id/evidence': {
      id: '/app/reports/$id/evidence'
      path: '/evidence'
      fullPath: '/app/reports/$id/evidence'
      preLoaderRoute: typeof AppReportsIdEvidenceRouteImport
      parentRoute: typeof AppReportsIdRoute
    }
  }
}

interface AppReportsIdRouteChildren {
  AppReportsIdEvidenceRoute: typeof AppReportsIdEvidenceRoute
}

const AppReportsIdRouteChildren: AppReportsIdRouteChildren = {
  AppReportsIdEvidenceRoute: AppReportsIdEvidenceRoute,
}

const AppReportsIdRouteWithChildren = AppReportsIdRoute._addFileChildren(
  AppReportsIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppInterviewsIdRoute: typeof AppInterviewsIdRoute
  AppInterviewsConsoleRoute: typeof AppInterviewsConsoleRoute
  AppJourneyIdRoute: typeof AppJourneyIdRoute
  AppReportsIdRoute: typeof AppReportsIdRouteWithChildren
  AppRolesIdRoute: typeof AppRolesIdRoute
  AppRolesNewRoute: typeof AppRolesNewRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppInterviewsIdRoute: AppInterviewsIdRoute,
  AppInterviewsConsoleRoute: AppInterviewsConsoleRoute,
  AppJourneyIdRoute: AppJourneyIdRoute,
  AppReportsIdRoute: AppReportsIdRouteWithChildren,
  AppRolesIdRoute: AppRolesIdRoute,
  AppRolesNewRoute: AppRolesNewRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiscoveryRoute: DiscoveryRoute,
  PlaygroundEvidenceRoute: PlaygroundEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
